# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARMtemplatesSvcCon'
    subscriptionId: '0a2f82ec-8354-43f9-a04d-20a9a211934c'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Azpipeline-RG'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/ravigrandhe/ravigran-azurerepo/main/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName ARMTemplates'
    deploymentMode: 'Incremental'
    deploymentOutputs: 'DeploymentPipelineTemplate'